baseURL = 'https://skyforest.org/'
languageCode = 'zh_CN' # en-us
title = '小森林'
theme = 'ananke'

[params]
  text_color = "white"
  author = ""
  favicon = ""
  site_logo = ""
  description = "Little forest, a wonderful land"
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 3

